name: mysql_client_fork
description: Native MySQL client written in Dart. Tested with MySQL Percona Server (5.7, 8), MariaDB (10). Supports TLS.
version: 0.1.0
homepage: https://github.com/CrewLAB/mysql_client_fork
repository: https://github.com/CrewLAB/mysql_client_fork
issue_tracker: https://github.com/CrewLAB/mysql_client_fork/issues

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  async: ^2.10.0
  buffer: ^1.2.2
  charcode: ^1.3.1
  collection: ^1.15.0
  crypto: ^3.0.3
  logger: ^2.0.2+1
  meta: ^1.8.0
  pool: ^1.5.1
  rxdart: ^0.28.0
  sasl_scram: ^0.1.0
  stream_channel: ^2.1.1
  tuple: ^2.0.2
dev_dependencies:
  hex: ^0.2.0
  mocktail: ^1.0.4
  test: ^1.25.2

